AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  InstanceType:
    Type: String
  AmiId:
    Type: AWS::EC2::Image::Id
  PemKey:
    Type: AWS::EC2::KeyPair::KeyName
  Subnet:
    Type: AWS::EC2::Subnet::Id

Resources:
  myInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      KeyName: !Ref PemKey
      SubnetId: !Ref Subnet
      Tags:
      {% for tag in config['tags'] %}
      - Key: {{ tag }}
        Value: {{ config['tags'][tag] }}
      {% endfor %}
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -v

          apt-get update
          apt-get install nginx -y
          apt-get install openjdk-7-jdk -y
          wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo
          sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources
          apt-get update
          apt-get install jenkins -y


