AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  cidr:
    Type: String
  {% for az in range(1,4) %}
  subnetCidr{{ loop.index }}:
    Type: String
  {% endfor %}
  internetRoute:
    Type: String

Resources:
  myVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref cidr
      Tags:
      {% for tag in config['tags'] %}
      - Key: {{ tag }}
        Value: {{ config['tags'][tag] }}
      {% endfor %}

  myInternetGateaway:
    Type: "AWS::EC2::InternetGateway"
    Properties: 
      Tags:
      {% for tag in config.tags %}
      - Key: {{ tag }}
        Value: {{ config.tags[tag] }}
      {% endfor %}

  myRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref myVPC
      Tags:
      {% for tag in config.tags %}
      - Key: {{ tag }}
        Value: {{ config.tags[tag] }}
      {% endfor %}

  myGWAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties: 
      InternetGatewayId: !Ref myInternetGateaway
      VpcId: !Ref myVPC

  {% for az in range(1,4) %}
  mySubnet{{ loop.index }}:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: !Ref subnetCidr{{ loop.index }}
      MapPublicIpOnLaunch: true
      Tags:
      {% for tag in config.tags %}
      - Key: {{ tag }}
        Value: {{ config.tags[tag] }}
      {% endfor %}
      VpcId: !Ref myVPC
  {% endfor %}


  myRoute:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: !Ref internetRoute
      GatewayId: !Ref myInternetGateaway
      RouteTableId: !Ref myRouteTable

  {% for i in range(1,4) %}
  mySubnetRouteAssoc:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref myRoute
      SubnetId: !Ref mySubnet{{loop.index}}
  {% endfor %}



Outputs:
  VpcId:
    Description: The VPC Id
    Value: !Ref myVPC
  
  {% for i in range(1,4) %}
  SubnetId{{loop.index}}:
    Description: The subnet id
    Value: !Ref mySubnet{{loop.index}}
  {% endfor %}
  
  RouteTableId:
    Description: The route table Id
    Value: !Ref myRouteTable

  IGWid:
    Description: The IGW Id
    Value: !Ref myInternetGateaway